#!/bin/sh
echo -e "\n###########################################################################"
echo -e   "#                                                                         #"
echo -e   "#                         Hello! It's level 1503                          #"
echo -e   "#                                                                         #"
echo -e   "#                    Find flag using zip util and bash                    #"
echo -e   "#                                                                         #"
echo -e   "###########################################################################"
sh
