#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                   #"
echo -e   "#       Hello! It's level 5         #"
echo -e   "#        try curl diary:80          #"
echo -e   "#                                   #"
echo -e   "#    No curl?! Try another way...   #"
echo -e   "#                                   #"
echo -e   "#      Pshhht! 'diary' host is      #"
echo -e   "#        your's neighbour ip.       #"
echo -e   "#                                   #"
echo -e   "####################################"
sh
