#!/bin/bash
echo -e "\n###########################################################"
echo -e   "#                                                         #"
echo -e   "#                 Hello! It's level 5902                  #"
echo -e   "#                                                         #"
echo -e   "#  Using external checker, wait for 1 min after solving   #"
echo -e   "#                                                         #"
echo -e   "#                Try cat diary.txt and git                #"
echo -e   "#                                                         #"
echo -e   "###########################################################"
bash
