#!/bin/sh
echo -e "\n########################################"
echo -e   "#                                      #"
echo -e   "#       Hello! It's level 1204         #"
echo -e   "#                                      #"
echo -e   "#           Use sed to find            #"
echo -e   "#            the FLAG_PART             #"
echo -e   "#                                      #"
echo -e   "########################################"
sh
