#!/bin/sh
echo -e "\n###########################################"
echo -e   "#                                          #"
echo -e   "#         Hello! It's level 0804           #"
echo -e   "#                                          #"
echo -e   "#   This is external checker type level.   #"
echo -e   "#      Wait for 1 min after solving        #"
echo -e   "#                                          #"
echo -e   "#   find&copy the whole diary content      #"
echo -e   "#      from level 27 and put it in         #"
echo -e   "#           /home/suzen/diary              #"
echo -e   "#   (flag will appear in /home/suzen)      #"
echo -e   "#                                          #"
echo -e   "###########################################"

sh