#!/bin/bash
echo -e "\n#############################################"
echo -e   "#                                           #"
echo -e   "#       Hello! It's level 1903              #"
echo -e   "#                                           #"
echo -e   "#     THIS IS OSTEP/3 LEVEL. READ DIARY     #"
echo -e   "#                                           #"
echo -e   "#############################################"
bash