#!/bin/bash
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 8        #"
echo -e   "# I'm suzen and this is my diary.. #"
echo -e   "#                                  #"
echo -e   "####################################"
rm /bin/hello
exec -a "/bin/bash/some/trash/for/you_not_to_use_grep/dmFlS//mFpc//GhvaGI4//Y29o//Z2gx//eWEK/" bash
