#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                   #"
echo -e   "#       Hello! It's level 0604      #"
echo -e   "#                                   #"
echo -e   "#      just list files in dir       #"
echo -e   "#                                   #"
echo -e   "####################################"
sh
