#!/bin/bash
echo -e "\n####################################"
echo -e   "#                                   #"
echo -e   "#       Hello! It's level 2002      #"
echo -e   "#                                   #"
echo -e   "#      you can sort out everyone    #"
echo -e   "#        but some are different     #"
echo -e   "#                                   #"
echo -e   "#        shh... unzip can help      #"
echo -e   "#                                   #"
echo -e   "####################################\n"
bash