FROM alpine
RUN mkdir -p /home/suzen/ \
    && echo "this is password for next level" > /home/suzen/.bmVlNm1lMEhhaU11M2thaGVpNmEK

#ADD diary.txt /home/suzen/
ADD hello /bin/hello

ENTRYPOINT ["/bin/hello"]
WORKDIR /home/suzen
