#!/bin/sh
echo -e "\n#############################################"
echo -e   "#                                           #"
echo -e   "#          Hello! It's level 2001           #"
echo -e   "#                                           #"
echo -e   "#       The variable containing the         #"
echo -e   "#         flag is still in memory!          #"
echo -e   "#            Use sed to get it              #"
echo -e   "#                                           #"
echo -e   "#############################################"
sh
