#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#     Hello! It's level 2001       #"
echo -e   "#                                  #"
echo -e   "#       These variable are         #"
echo -e   "#        still in memory!          #"
echo -e   "#                                  #"
echo -e   "####################################"
sh
