#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                     Hello! It's level 23                             #"
echo -e   "#                                                                      #"
echo -e   "#  This is external checker type level. Wait for 1 min after solving   #"
echo -e   "#                                                                      #"
echo -e   "#  1) rename all files in destination folder, adding '.back' to name   #"                                                              #"
echo -e   "#  2) move everything from source folder to destination folder         #"
echo -e   "#         and flag will appear in this directory:   ~suzen             #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
