#!/bin/sh
echo -e "\n########################################"
echo -e   "#                                      #"
echo -e   "#       Hello! It's level 1203         #"
echo -e   "#         You need to decode           #"
echo -e   "#             the flag!                #"
echo -e   "#                                      #"
echo -e   "########################################"
sh
