FROM busybox
RUN mkdir /home/suzen \
    && mkdir -p /home/suzen/part1/d2FodmFoM \
    && mkdir -p /home/john/Documents/part2/WFlV2FpYm \
    && mkdir -p /home/john/Desktop/part3/VlaG9vMmIK


ADD diary.txt /home/suzen/
ADD hello /bin/hello

ENTRYPOINT ["/bin/hello"]
WORKDIR /home/suzen
