#!/bin/bash
if [ ! -f /var/tmp/addr ]; then
  echo 1 > /var/tmp/addr
fi
addr=$(cat /var/tmp/addr)
if [ "$addr" -gt 254 ] || [[ "$addr" == "" ]]; then
  addr="1"
  /etc/cron.hourly/kill-docker.sh 2>&1 1>/dev/null
fi

NETWORK=$(( RANDOM % 1000000000))
docker network create --internal --subnet 10.10.${addr}.0/24 ${NETWORK} 2>&1 1>/dev/null
((addr++))
echo ${addr} > /var/tmp/addr

if [ "$(whoami)" == "suzen5" ]; then
  #/usr/bin/docker run -ti -d --rm --network $NETWORK --cpus=".2" --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 --storage-opt size=11G ctf.school:5000/suzene$
   /usr/bin/docker run -ti -d --rm --network $NETWORK --cpus=".2" --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 ctf.school:5000/suzenescape/suzen5server 2>/dev/null
fi
#/usr/bin/docker run -ti --rm --network $NETWORK --cpus=".2" --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 --storage-opt size=11G ctf.school:5000/suzenescape$
 /usr/bin/docker run -ti --rm --network $NETWORK --cpus=".2" --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 ctf.school:5000/suzenescape/$(whoami) 2>/dev/null
