#!/bin/bash
echo -e "\n#############################################"
echo -e   "#                                           #"
echo -e   "#       Hello! It's level 2502              #"
echo -e   "#                                           #"
echo -e   "#       Give such rights to diary.txt :     #"
echo -e   "#           -Owner only to Write,           #"
echo -e   "#           -Group only to Read             #"
echo -e   "#           -Others to Read and Write       #"
echo -e   "#    And write "SuzenEscape" to diary.txt     #"
echo -e   "# Wait for 1 minute and the flag will appear#"
echo -e   "#                                           #"
echo -e   "#############################################"
bash
