#!/bin/sh
echo -e "\n###########################################"
echo -e   "#                                         #"
echo -e   "#         Hello! It's level 27            #"
echo -e   "#                                         #"
echo -e   "#   that's so easy! print file contents   #"
echo -e   "#             (continuously)              #"
echo -e   "#                                         #"
echo -e   "###########################################"

/bin/init & 2>/dev/null

sh
