- name: get values
  set_fact: 'user={{ levels_item }}'

- debug: var=user.name

- debug: var=user.password

- name: generate password
  shell: "echo {{ token | default('latest:1234567890') }} | openssl enc -aes-256-cbc -nosalt -k {{ user.password }} -a | base64"
  register: password_encrypted

- debug: var=password_encrypted.stdout

- name: set password varible
  set_fact: password="{{ password_encrypted.stdout }}"

- debug: var=password

- name: re-set password var if it is first-chain-level password
  set_fact: password="{{ user.password }}"
  when: '"suzen" in user.password'

- debug: var=password

- debug: msg="{{ password  | string | password_hash('sha512', user.sault) }}"

- name      : create users
  user      :
    name       : "{{ user.name }}"
    password   : "{{ password  | string | password_hash('sha512', user.sault) }}"
    shell      : /usr/local/bin/dockersh
    groups     : docker
    create_home: yes
  register: result

- debug: var=result