#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 0101     #"
echo -e   "#   try something of cat, ls, cd   #"
echo -e   "#                                  #"
echo -e   "####################################"
sh
