.\" Manpage for diary.
.\" Contact @bykva to correct errors or typos.
.TH man 8 "20 Feb 2019" "1.0" "diary man page"
.SH NAME
diary \- little girls' diary
.SH DESCRIPTION
diary is a book in which one keeps a daily record of events and experiences.
.SH OPTIONS
The diary does not take any options.
.SH FLAG
Y2hpZWNoM2VpRzRJZWtlaXNlbGUK
.SH BUGS
No known bugs.
.SH AUTHOR
bykva (@bykva)
