#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                   #"
echo -e   "#       Hello! It's level 18        #"
echo -e   "#                                   #"
echo -e   "#           RTFM diary!             #"
echo -e   "#                                   #"
echo -e   "####################################"
sh
