#!/usr/local/bin/bash
echo -e "\n###########################################################################"
echo -e   "#                                                                         #"
echo -e   "#                         Hello! It's level 1001                          #"
echo -e   "#    Have you ever hear about git? Try to find flag in commits.           #"
echo -e   "#                                                                         #"           
echo -e   "###########################################################################"
bash
