#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                   #"
echo -e   "#       Hello! It's level 15        #"
echo -e   "#                                   #"
echo -e   "#    determine current directory    #"
echo -e   "#                                   #"
echo -e   "####################################"
export PS1="~"
sh
