#!/bin/bash
echo -e "\n#############################################"
echo -e   "#                                           #"
echo -e   "#       Hello! It's level 1901              #"
echo -e   "#                                           #"
echo -e   "#     THIS IS OSTEP/2 LEVEL. READ DIARY     #"
echo -e   "#                                           #"
echo -e   "#############################################"
bash