#!/bin/bash
echo -e "\n######################################"
echo -e   "#                                    #"
echo -e   "#     Hello! It's level 1301         #"
echo -e   "#                                    #"
echo -e   "#   THIS IS ACL LEVEL. READ DIARY    #"
echo -e   "#                                    #"
echo -e   "######################################"
