#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                       Hello! It's level 20                           #"
echo -e   "#                                                                      #"
echo -e   "#  This is external checker type level. Wait for 1 min after solving   #"
echo -e   "#                                                                      #"
echo -e   "#        remove everything from ~john and flag will appear             #"
echo -e   "#                  in this directory:   ~suzen                         #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
