#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 0103     #"
echo -e   "#        only ls, really??         #"
echo -e   "#                                  #"
echo -e   "####################################"
sh
