#!/bin/sh
echo -e "\n###################################################################"
echo -e   "#                                                                 #"
echo -e   "#                  Hello! It's level 21                           #"
echo -e   "#                                                                 #"
echo -e   "#      remove the following:                                      #"
echo -e   "#      1) all txt files with numbers in their name                #"
echo -e   "#      2) all png files with lowercase letters in their name      #"
echo -e   "#      3) all test files, non-arhived                             #"
echo -e   "#                                                                 #"
echo -e   "#      and flag will appear in this directory: ~suzen             #"
echo -e   "#                                                                 #"
echo -e   "###################################################################"
sh