#!/usr/local/bin/bash
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 0503     #"
echo -e   "#           read diary.txt         #"
echo -e   "#                                  #"
echo -e   "####################################"
bash
