#!/bin/sh
echo -e "\n#############################################"
echo -e   "#                                           #"
echo -e   "#          Hello! It's level 1201           #"
echo -e   "#                                           #"
echo -e   "#          Use sed to get flag              #"
echo -e   "#                                           #"
echo -e   "#############################################"
sh
