#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 12       #"
echo -e   "#           read diary.txt         #"
echo -e   "#                                  #"
echo -e   "####################################"
sh
