#!/usr/local/bin/bash
echo -e "\n###########################################################################"
echo -e   "#                                                                         #"
echo -e   "#                         Hello! It's level 1002                          #"
echo -e   "#    Lets go on with git? In this task you will find out some info        #"
echo -e   "#    about branches, see you soon                                         #"
echo -e   "#                                                                         #"           
echo -e   "###########################################################################"

bash
