#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                       Hello! It's level 1002                         #"
echo -e   "#                                                                      #"
echo -e   "#                            Very easy!                                #"
echo -e   "#            Get the flag from this directory , read diary.            #"
echo -e   "#                                                                      #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
