#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 1401     #"
echo -e   "#                                  #"
echo -e   "####################################"
sh
