#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                       Hello! It's level 0706                         #"
echo -e   "#                                                                      #"
echo -e   "#  This is external checker type level. Wait for 1 min after solving   #"
echo -e   "#                                                                      #"
echo -e   "#             copy Desktop/music content to ~suzen/Music               #"
echo -e   "#            flag will appear in this directory:   ~suzen              #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
