#!/bin/bash
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 40       #"
echo -e   "#     This task is encrypted       #"
echo -e   "#      and shorthand               #"
echo -e   "#                                  #"
echo -e   "####################################"
sh

