#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 0102     #"
echo -e   "#        try something of          #"
echo -e   "#  ls|cd|cat|less|more|head|tail   #"
echo -e   "#  to read password from homedir   #"
echo -e   "#                                  #"
echo -e   "# Read Suzen diary for the details #"
echo -e   "#                                  #"
echo -e   "####################################\n"
sh
