#!/bin/sh
echo -e "\n###########################################################################"
echo -e   "#                                                                         #"
echo -e   "#                         Hello! It's level 1005                          #"
echo -e   "#  Try to find flag using commit changes.The flag is in file readme.txt   #"
echo -e   "#                                                                         #"           
echo -e   "###########################################################################"

sh
