---
- name: get timestamp
  shell: date +%Y-%m-%d-%H-%M-%S
  register: timestamp
  changed_when: false

- name: build'n'deploy web
  shell: |
    cd ../suzen_website && \
    docker build -t {{ registry_host }}/suzenescape/web:{{ timestamp.stdout }} . && \
    docker push {{ registry_host }}/suzenescape/web:{{ timestamp.stdout }}
  retries: 3
  delay: 3
  register: result
  until: result is not failed
  connection: local
  become: no

- name: ensure web service file
  copy:
    dest: /etc/systemd/system/web.service
    owner: root
    group: root
    mode: 0644
    content: |
      [Unit]
      Requires=docker.service
      After=docker.service
      StartLimitIntervalSec=0
      [Service]
      ExecStartPre=-/usr/bin/docker rm --force %N
      ExecStart=/usr/bin/docker run \
        --name=%N \
        --rm=true \
        --network=host \
        --stop-timeout=300 \
        {{ registry_host }}/suzenescape/web:{{ timestamp.stdout }}
      ExecStop=-/usr/bin/docker stop %N
      Restart=always
      RestartSec=10
      KillMode=process
      [Install]
      WantedBy=multi-user.target
  notify: restart web

- name: execute handlers
  meta: flush_handlers

- name: start web service
  systemd:
    name: web
    state: started
    enabled: yes
