#!/bin/bash

NAME="suzen6"

#for i in $(echo "YmllMWVraUQ0YWlxdWU5a2VpcGgK" | sed -e 's/\(.\)/\1 /g'); do echo $i | nc 127.0.0.1 1337 -w0; done
# tcpdump -i lo -n -nn 'port 1337' -s 65535 -w /tmp/pcap111
# nc -lvk 127.0.0.1 1337

#solving:
#tcpflow -r diary.pcap -c | cut -f2 -d : | egrep '^ [a-zA-Z0-9]$' |  tr -d ' \n' |wc
#
CURRENT_PASSWORD="dmVlNFdvaE42ZWVoMFpvN3dhcGgK"
NEXT_LEVEL_PASSWORD="YmllMWVraUQ0YWlxdWU5a2VpcGgK"
