#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                       Hello! It's level 24                           #"
echo -e   "#                                                                      #"
echo -e   "#             copy Desktop/music content to ~suzen/Music               #"
echo -e   "#            flag will appear in this directory:   ~suzen              #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
