#!/bin/sh
echo -e "\n######################################"
echo -e   "#                                    #"
echo -e   "#     Hello! It's level 1403         #"
echo -e   "#                                    #"
echo -e   "#   THIS IS LPE LEVEL. READ DIARY    #"
echo -e   "#                                    #"
echo -e   "######################################"

bash
