#!/bin/sh
echo -e "\n##################################"
echo -e   "#                                 #"
echo -e   "#     Hello! It's level 0502      #"
echo -e   "#                                 #"
echo -e   "##################################"
sh  
