#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                      Hello! It's level 0504                          #"
echo -e   "#               Find flag. Unpack some archives                        #"
echo -e   "#                                                                      #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
