#!/bin/sh
echo -e "\n####################################"
echo -e   "#                                  #"
echo -e   "#       Hello! It's level 0302     #"
echo -e   "# I'm suzen and this is my diary.. #"
echo -e   "#                                  #"
echo -e   "####################################"
bash
