#!/bin/bash
echo -e "\n#############################################"
echo -e   "#                                           #"
echo -e   "#         Hello! It's level 1902            #"
echo -e   "#                                           #"
echo -e   "#     THIS IS OSTEP/1 LEVEL. READ DIARY     #"
echo -e   "#                                           #"
echo -e   "#############################################"
bash