#!/bin/bash
echo -e "\n####################################"
echo -e   "#                                   #"
echo -e   "#       Hello! It's level 1506      #"
echo -e   "#                                   #"
echo -e   "#     do you know death archve?     #"
echo -e   "#                                   #"
echo -e   "####################################\n"
bash