#!/bin/sh
echo -e "\n########################################################################"
echo -e   "#                                                                      #"
echo -e   "#                       Hello! It's level 2301                         #"
echo -e   "#                                                                      #"
echo -e   "#                                                                      #"
echo -e   "#                   Find flag in chest, read diary.                    #"
echo -e   "#                                                                      #"
echo -e   "#                                                                      #"
echo -e   "########################################################################"
sh
